---

name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      statuses: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@9e86335
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
